### ISSUE TITLE
¿Qué dinamic bitset?

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#1]
En la versión de 2016, que usamos para medir prestaciones, se usaba bitset de `tr2` (que no sé qué es lo que es). ¿Hay diferencia entre este y el de la BOOST? ¿O es porque este es dinámico?

https://github.com/gstvrmrlpz/energy/blob/461f11b7e239670e552b89c49419b04a83ee465d/c%2B%2B/dynamic-bitset.cc#L3

**Comment by gstvrmrlpz** [comment]
bitset tiene la limitación de que hay que conocer el tamaño en tiempo de compilación por eso también probé el dynamic_bitset de boost que no la tiene.
Mucho más conveniente para un caso general.

**Comment by gstvrmrlpz** [comment]
TR2 es un técnical report versión 2, una implementación experimental.
Así lleva muchos años sin finalizarse.
He añadido otra versión para comparar boost con std::tr2, ya decidiremos con cuál quedarnos pero parecen bastante parejas.

**Comment by JJ** [comment]
Sería interesante compararlas, igual.

**Comment by gstvrmrlpz** [comment]
Ya las he comparado y son tan iguales que no merece la pena tener las dos.
Así que he eliminado boost para no depender de otra biblioteca más, ya la otra versión viene incluida con el gcc.
