### ISSUE TITLE
Try different compilers

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#10]
At least llvm and possibly Clang (for Intel, right)?

**Comment by gstvrmrlpz** [comment]
He probado gcc y clang. Cada uno tiene sus puntos fuertes...

```
gustavo@casa:~/escritorio/energy/c++$ make compilers 
------------------------------------------------
     program    compiler   energy(J)     time(s)
------------------------------------------------
      bitset     clang++       37,46    1,252416
      bitset         g++       34,74    1,195120
      string     clang++       27,41     0,95308
      string         g++       34,48    1,179314
      vector     clang++       41,76    1,392489
      vector         g++       35,38     1,20867

```

**Comment by JJ** [comment]
Interesante.
Para poder usarlo en el paper necesitaría los ficheros con  #11 y con las otras cosas que hemos dicho. Con todo, interesante.

**Comment by gstvrmrlpz** [comment]
no me ha dado tiempo hoy.
dejo esto para en martes 9 :)

**Comment by JJ** [comment]
Mira de todas formas el milestone en el que está. Poco a poco...

**Comment by gstvrmrlpz** [comment]
Los compiladores de amd e intel están basados en clang++ de llvm.
Tras probarlos y comprobar que ofrecen un rendimiento similar creo que podemos obviarlos.

**Comment by JJ** [comment]
Eso escrito en el paper quedaría fenomenal.
