### ISSUE TITLE
Making long chunks of code scripts makes easier programming/debugging

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#12]
Or converting it in other languages...

https://github.com/gstvrmrlpz/energy/blob/9e1f6f97ee1271fc14c44824bd10ace9d4d3498e/c%2B%2B/makefile#L48-L62

**Comment by JJ** [comment]
Puedes poner lo mismo en un shell script que se llame desde ahí. Sólo usa `$(SIZ)`

**Comment by gstvrmrlpz** [comment]
Cuestión de preferencias personales el tenerlo todo junto en un mismo sito.
