### ISSUE TITLE
¿Por qué probamos diferentes longitudes de cromosoma y no direfentes tamaños de población?

### ISSUE THREAD

**Issue by gstvrmrlpz** [gstvrmrlpz/energy#14]

**Comment by JJ** [comment]
Sería interesante si estuviéramos trabajando con un nivel superior: selección, por ejemplo; en ese caso el tamaño de la población si interaccionaría de forma no lineal con el resto de los parámetros. En este caso, no creo que arrojara ningún resultado interesante más allá de que aumenta de forma más o menos lineal el consumo con el tamaño de población (y ocupación de memoria correspondiente).

En realidad, ni siquiera tenemos una población; son simplemente un número fijo de llamadas a una función (o grupo de funciones). Si decidimos que la estructura de datos en la que se almacena la población, o como se trabaja con ella, tiene un efecto crítico en el consumo de energía, puede que sea interesante. Pero ahora mismo, no veo ninguna pregunta de investigación que se pueda contestar haciendo más llamadas a la función que se quiere probar.
