### ISSUE TITLE
El paso 0 no es necesario

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#15]
Con cubrir lo que se tarda en inicializar es suficiente.

https://github.com/gstvrmrlpz/energy/blob/6540bfb6c7e6d99e633b716abbaa86a092cbb5f4/c%2B%2B/common.h#L77-L78

El paso 0 no va diferenciar para diferentes métodos porque en lo único que se van a diferenciar a priori es en el tamaño del ejecutable, y eso va a tener muy poca influencia.

**Comment by gstvrmrlpz** [comment]
perdona... no he actualizado la página de issues y este no me salía... perdón
