### ISSUE TITLE
Move results to specific directory

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#19]
And, while you're at it, try to use uniform names for files, including date, for instance, and machine-ids (Intel, AMD...)

Also eliminate data from tests, or those that do not conform to the format. For the time being. For the time being there is no file that follows that format #13 , is that correct?

**Comment by JJ** [comment]
Eso ya se discutió en #13 , ¿no se quedó solucionado?

**Comment by gstvrmrlpz** [comment]
no, lo que decidimos era el formato interno de los ficheros de datos, no su nombre

**Comment by JJ** [comment]
Literalmente dice "file names" en el issue... Lo digo simplemente para que lo hablemos ahí

**Comment by gstvrmrlpz** [comment]
hecho desde julio
