### ISSUE TITLE
Decide which computers we have available and

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#20]
We have
* `casa`
* `pccito`
* I have an Intel laptop and an AMD desktop. What are the characteristics of the two above?

We are looking at research question 4 mainly here #17

**Comment by gstvrmrlpz** [comment]
El servidor que reinstalé con el nombre "amd" parece ir bien, lo único malo es que se parece demasiado a pccito :(
Como bueno que está totalmente libre :(
También tengo el portátil Dell XPS de 2017 que tiene micro intel.

**Comment by gstvrmrlpz** [comment]
depende de cada trabajo así que no es necesario discutirlo de nuevo
