### ISSUE TITLE
Incluir en el README.md los settings que necesita perf

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#3]
Y como hacerlo

**Comment by gstvrmrlpz** [comment]
Perf no se lleva demasiado bien con la medición de energía. 
"perf stat" funciona bien pero "perf record" no.
Este punto tengo que investigarlo un poco más a ver si pudiesemos desglosar el consumo de energía de la misma forma que otros tipos de eventos.

**Comment by gstvrmrlpz** [comment]
pinpoint tampoco me permite medir más cosas...

  sudo ./pinpoint -l
  List of available counters (to be used in -e):
	  rapl:pkg

**Comment by JJ** [comment]
> pinpoint tampoco me permite medir más cosas...
> 
> ```
>   sudo ./pinpoint -l
>   List of available counters (to be used in -e):
>       rapl:pkg
> ```

En los AMD sí. También GPU, porque esa la saca de nvml si lo tienes instalado.

**Comment by JJ** [comment]
En todo caso, yo conseguí echarlo andar en el portátil Intel y en el AMD. Tienes que meterte en un shell de root y escribir

```
echo -1 > /proc/sys/kernel/perf_event_paranoid
```

**Comment by gstvrmrlpz** [comment]
ya tenía un script para eso:

        #!/usr/bin/env bash
        
        if [ "${#@}" == "0" ]; then
	        sysctl kernel.perf_event_paranoid
	        echo "  -1: Allow use of (almost) all events by all users"
	        echo "      Ignore mlock limit after perf_event_mlock_kb without CAP_IPC_LOCK"
	        echo ">= 0: Disallow raw and ftrace function tracepoint access"
	        echo ">= 1: Disallow CPU event access"
	        echo ">= 2: Disallow kernel profiling"
        else
	        sudo sysctl kernel.perf_event_paranoid=${1-1} # 1 by default
        fi

**Comment by JJ** [comment]
Añade un target en make para eso, o en CMake si lo usas.

**Comment by gstvrmrlpz** [comment]
añadido
