### ISSUE TITLE
Probar opciones de compilación

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#4]
Probar con diferentes opciones de compilación. 

- O2
- O4

## Opciones de compilación

- AVX
- SSE

**Comment by gstvrmrlpz** [comment]
En mi opinión deberíamos dejar sólo las opciones más importantes -O2 y -O3.
Tampoco aporta nada dejar o eliminar SIMD.

**Comment by JJ** [comment]
Los primeros resultados de cada serie tardan mucho más tiempo que el resto.
Por otro lado, como digo en otro issue, convendría tener resultados de cada
ejecución por separado.

**Comment by gstvrmrlpz** [comment]
Estas pruebas solo sirven para determinar que dirección vamos a seguir en el trabajo.
Lo de tener los resultados por separado solo puede hacerse repitiendo muchas veces los experimentos y como comentas ya lo hemos aclarado.

**Comment by JJ** [comment]
> Estas pruebas solo sirven para determinar que dirección vamos a seguir en el trabajo. Lo de tener los resultados por separado solo puede hacerse repitiendo muchas veces los experimentos y como comentas ya lo hemos aclarado.

Incluso así, en un diseño experimental hay que incorporar esas pruebas a la parametrización de los experimentos. Se pueden hacer algunas pruebas iniciales para descartar, pero incluso así habría que apoyarse en la estadística.

**Comment by gstvrmrlpz** [comment]
ya hemos escogido -O2 y -O3 tras haber probado un conjunto más amplio de opciones.

**Comment by JJ** [comment]
Eso debería ir al paper, ¿no?
