### ISSUE TITLE
¿Hay estructuras de datos que sean bitpacked?

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#5]
Quizás usar estructuras de datos bitpacked como Unions

**Comment by gstvrmrlpz** [comment]
bitset y vector<bool> ya son "bit packed".
std::string no puesto que consume un "char" por cada bit.

**Comment by JJ** [comment]
Dejo abierto para añadir a documentación.

**Comment by gstvrmrlpz** [comment]
Classification of data structures:
1. bitset.cc: bitpacked
2. bvector.cc: bitpacked
3. cvector.cc: no bitpacked
4. dbitset.cc: bitpacked
5. string.cc: no bitpacked

**Comment by gstvrmrlpz** [comment]
hecho antes del verano...
