### ISSUE TITLE
Probar crossover de dos puntos

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#6]
En vez del de un punto

**Comment by gstvrmrlpz** [comment]
El cruce de dos puntos es todavía más ligero que el de 1 punto...
¿Cuál es el objetivo de este cambio?

**Comment by JJ** [comment]
Simplemente usar la carga de trabajo habitual en algoritmos genéticos, que usan crossover de dos puntos en general. Como es más ligera, por eso se combina como se dice en #7 . En todo caso, como se ha medido para zig de esa forma, es más fácil comparar con las medidas en zig, que ya están hechas (y publicadas)

**Comment by gstvrmrlpz** [comment]
ya implementado hace tiempo
