### ISSUE TITLE
Programar HIFF

### ISSUE THREAD

**Issue by JJ** [gstvrmrlpz/energy#8]
HIFF es una función bastante pesada.

**Comment by gstvrmrlpz** [comment]
En el problema onemax no hay dependencias entre bloques de cromosomas así que no tengo nada claro si tendría sentido aplicar HIFF en este problema.

**Comment by JJ** [comment]
onemax lo vamos a aplicar de todas formas. HIFF tiene varias cosas. Para empezar, es más "pesado", con lo cual es más fácil apreciar diferencias. Para continuar, es recursivo con lo que lo que se meta y saque de la pila va a tener mucha más influencia.

**Comment by gstvrmrlpz** [comment]
hiff lo tienes ya programado para onemax para que pueda echarle un vistazo?

**Comment by JJ** [comment]
No es para onemax, es otra función de fitness diferente.
Si te sirve zig:
https://github.com/JJ/energy-ga-icsoft-2023/blob/main/code/zig/src/HIFF.zig

Pero vamos, seguro que hay por ahí alguna implementación en C++. En el mismo repo hay implementaciones en Kotlin y Javascript, y no sé si en Elixir.

**Comment by gstvrmrlpz** [comment]
ya lo tengo implementado... sustituyo onemax por hiff?

**Comment by JJ** [comment]
No, #7 dice que van todos en una misma iteración del bucle, este va aparte. Son dos programas diferentes, uno para crossover,mutación,onemax y otro para HIFF

**Comment by JJ** [comment]
Podíamos intentar PRs para incorporar nuevo código, así se va viendo lo que se va haciendo... Te refieres al issue en el que está y listo, y luego cuando se cierre se sabe qué issue es el que se ha hecho.

**Comment by gstvrmrlpz** [comment]
hecho
